#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_4,    Continuous,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//








task main()
{
  servo[Continuous] = 255;

  wait1Msec(5000);
  servo[Continuous] = 0;
}
