#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     HTSMUX,              sensorNone)
#pragma config(Sensor, S3,     Accelerometer,       sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          Conveyor,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          IndicatorLight, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    Kicker,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    Slide,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    Door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "shared/include.c"
#include "TeleOp/include.c"
#include "Autonomous/include.c"




#define kSidewindAngle PI / 30
#define kSidewindDistance .75


task main()
{
  Controller primary;


  while ( true )
  {
    UpdatePrimaryController(primary);
    motor[Left] = primary.leftJoystick.y * 100;
    motor[Right] = primary.rightJoystick.y * 100;
  }







  //nMotorEncoder[Left] = 0;
  /*
  motor[Left] = -1000;
  wait1Msec(210);
  motor[Left] = 0;

  wait10Msec(1000);
  */


  /*
  float original = PI / 2;
  CurrentRobotPosition.orientation = original;

  int count = 200;
  for ( int i = 0; i < count; i++ )
  {
    RobotRotateToOrientation(original + kSidewindAngle);
    RobotMoveDistance(kSidewindDistance, false);
    RobotRotateToOrientation(original - kSidewindAngle);
    RobotMoveDistance(-kSidewindDistance, false);


  }

  RobotRotateToOrientation(original);
  */
}
