#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ElevatorTop,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Elevator,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
bool vibrating = false;
task main()
{
  if ( vibrating ) return;
  vibrating = true;

  PlaySound(soundBeepBeep);

  motor[Elevator] = -30;
  wait1Msec(75);
  motor[Elevator] = 30;
  wait1Msec(75);
  while ( !SensorValue[ElevatorTop] ) {}
  motor[Elevator] = 0;
}
*/




bool doingStuff = false;
task doStuff()
{


  //hogCPU();
  if ( doingStuff )
  {
    //releaseCPU();
    return;
  };

  doingStuff = true;
  //releaseCPU();




  PlaySound(soundBeepBeep);

  //hogCPU();
  wait10Msec(100);
  //releaseCPU();


  PlaySound(soundDownwardTones);

  doingStuff = false;
}




task main()
{
  while ( true )
  {
    if ( !doingStuff ) StartTask(doStuff);

    //EndTimeSlice();
  }
}
