#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



#include "Lib/include.c"



void setStartInfo()
{
	FTCTeamSetCurrent(FTCTeamRed);					//	tell it what team we are on
	FTCFieldSetStartPosition(FTCStartPositionLeft);	//	tell it which start square we're on
}



void initializeRobot()
{
	FTCFieldInit();	//  initialize the map of the field

	setStartInfo();
	
	
	//	FIXME: init mechanism???
	
	
	PlaySound(soundUpwardTones);
}



static bool gettingDoubler;	//	global variable that tells whether or not the GetDoublerBaton task is running

task GetDoublerBaton()
{
	gettingDoubler = true;
	
	
	KeyPointID dispenserID = FTCFieldGetKeyPointOfCenterDispenserForTeam(FTCTeamGetCurrent());	//	get key point of the dispenser
	//	FIXME: go to the dispenser
	//	FIXME: turn towards it
	RobotMountCenterDispenser();	//	get aligned with the dispenser
	//	FIXME: run the conveyor to get batons
	//	FIXME: backup to node
	
	
	gettingDoubler = false;
}



task GetToBridgeAndBalance()
{
	FTCFIeldGetKeyPointOfBridgeForTeam(FTCTeamGetCurrent());	//	FIXME: what about the other bridge????
	//	FIXME: go to the key point
	
	RobotBalance();
}




task main()
{
	initializeRobot();
	
	waitForStart();		// Wait for the beginning of autonomous phase.
	
	long startTime = nPgmTime;
	
	
	StartTask(GetDoublerBaton);
	
	while ( nPgmTime - startTime < 25000 && gettingDoubler )	//	wait until 25 seconds are up or we have the doubler
	{
		wait10Msec(100);	//	wait 1 second
	}
	
	StartTask(GetToBridgeAndBalance);
}



