#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



#include "include.c"




void initializeRobot()
{
	// FIXME: implement


	FTCFieldInit();  //  initialize the map of the field



	//MapSetCurrentNodeID(NodeIDRedStartSquareLeft);  //  set starting position



	RobotPosition position;
	Vector2DMake(50, 50, position.location);
	position.orientation = 0;
	//	TrackerSetCurrentPosition(position);
	
	
	
	
	PlaySound(soundUpwardTones);


	return;
}



task main()
{
	initializeRobot();

	//waitForStart(); // Wait for the beginning of autonomous phase.

  //RobotGoToNode(NodeIDBlueStartSquareRight);


	//	FIXME: implement
}
