#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Elevator,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//







task main()
{
  while ( true )
  {
    if ( nNxtButtonPressed == kLeftButton )
    {
      motor[Elevator] = 20;
    }
    else if ( nNxtButtonPressed == kRightButton )
    {
      motor[Elevator] = -20;
    }
    else
    {
      motor[Elevator] = 0;
    }
  }
}
