#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     LeftLightSensor,     sensorLightActive)
#pragma config(Sensor, S2,     RightLightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          Left,          tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S3_C1_1,    Kicker,               tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    Door,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    Slide,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#define IndicatorLight 3
#define Conveyor 2

#include "shared/include.c"
#include "Autonomous/include.c"




task main()
{
  /*
  while ( true )
  {
    nxtDisplayCenteredTextLine(0, (string)LEFT_LIGHT_SENSOR);
  }*/


  LineFollowingContext ctxt;
  ctxt.lineBrightness = 47;
  ctxt.surroundingBrightness = 28;

  RobotFollowWhiteLineToEnd(ctxt, false);


  motor[Left] = 30;
  motor[Right] = 30;

  wait10Msec(1000);
}
