#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ElevatorTopStop,     sensorTouch)
#pragma config(Sensor, S3,     SMUX2,               sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX1,               sensorI2CCustom)
#pragma config(Motor,  motorA,          IndicatorLight, tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  motorC,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_5,    Servo,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "joystickDriver.c"




#define kPositionIncrement 1


task main()
{
	//waitForStart();   // wait for start of tele-op phase



	short position = 255 / 2;
	long lastUpdate;
	long updateInterval = 30;
	//Controller controller;

	while (true)
	{
		//UpdatePrimaryController(controller);


/*
			if ( ControllerButtonIsPressed(controller, ControllerButton4) )
			{
			  updateInterval = 130;
			}
			else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
			{
			  updateInterval = 25;
			}

*/





		if ( nPgmTime > (lastUpdate + updateInterval) )
		{
		  if ( nNxtButtonPressed == kRightButton )
      {
		    position += kPositionIncrement;
        lastUpdate = nPgmTime;
      }
      else if ( nNxtButtonPressed == kLeftButton )
      {
		    position -= kPositionIncrement;
        lastUpdate = nPgmTime;
      }


      if ( position > 255 ) position = 255;
      if ( position < 0 ) position = 0;
		}


		servo[Servo] = position;
		nxtDisplayCenteredTextLine(2, (string)position);
	}
}
