#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ElevatorTopStop,     sensorTouch)
#pragma config(Sensor, S3,     SMUX2,               sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX1,               sensorI2CCustom)
#pragma config(Motor,  motorA,          IndicatorLight, tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  motorC,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Elevator,      tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Kicker,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    Gate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Slide,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    RightStomper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    LeftStomper,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//  SMUX1
#define Magnet msensor_S4_4
#define Sonar msensor_S4_3
#define Accelerometer msensor_S4_2


//  SMUX2
#define ElevatorBottomStop msensor_S3_1
#define IR msensor_S3_2
#define LeftLightSensor msensor_S3_3
#define RightLightSensor msensor_S3_4
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////




#include "shared/include.c"
#include "TeleOp/include.c"






#define kPositionIncrement 1


task main()
{
	waitForStart();   // wait for start of tele-op phase



	short position = 255 / 2;
	int lastUpdate;
	int updateInterval = 30;
	Controller controller;

	while (true)
	{
		UpdatePrimaryController(controller);



		if ( ControllerButtonIsPressed(controller, ControllerButton4) )
		{
		  updateInterval = 130;
		}
		else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
		{
		  updateInterval = 25;
		}







		if ( nPgmTime > (lastUpdate + updateInterval) )
		{
		  if ( controller.dPad.y == 1 )
      {
		    position += kPositionIncrement;
        lastUpdate = nPgmTime;
      }
      else if ( controller.dPad.y == -1)
      {
		    position -= kPositionIncrement;
        lastUpdate = nPgmTime;
      }


      if ( position > 255 ) position = 255;
      if ( position < 0 ) position = 0;
		}


		servo[Gate] = position;
		nxtDisplayCenteredTextLine(2, (string)position);
	}
}
