#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  motorA,          Conveyor,      tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          IndicatorLight, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    Servo,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#define Sonar 1
#define Magnetic 2
#define Slide 3
#define DoorLeft 3
#define DoorRight 4



#include "shared/include.c"
#include "TeleOp/include.c"






#define kPositionIncrement 1


task main()
{
	waitForStart();   // wait for start of tele-op phase



	short position = 255 / 2;
	int lastUpdate;
	int updateInterval = 30;
	Controller controller;

	while (true)
	{
		UpdatePrimaryController(controller);



		if ( ControllerButtonIsPressed(controller, ControllerButton4) )
		{
		  updateInterval = 130;
		}
		else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
		{
		  updateInterval = 25;
		}







		if ( nPgmTime > (lastUpdate + updateInterval) )
		{
		  if ( controller.dPad.y == 1 )
      {
		    position += kPositionIncrement;
        lastUpdate = nPgmTime;
      }
      else if ( controller.dPad.y == -1)
      {
		    position -= kPositionIncrement;
        lastUpdate = nPgmTime;
      }


      if ( position > 255 ) position = 255;
      if ( position < 0 ) position = 0;
		}


		servo[Servo] = position;
		nxtDisplayCenteredTextLine(2, (string)position);
	}
}
