#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Magnetic,            sensorHiTechnicMagnetic)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          Conveyor,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          IndicatorLight, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Front,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Back,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Kicker,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    Slide,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#include "Lib/include.c"


void initializeRobot()
{
	//	FIXME: implement

	MechanismInit();


	return;
}



#define kLowPower .2
#define kRegularPower .4
#define kHighPower .8



void DriveControl(Controller& controller)
{
    //  power
  /*
    if ( ControllerButtonIsPressed(controller, ControllerButton1) )
    {
      SetPowerMultiplier(kLowPower);
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
    {
      SetPowerMultiplier(kRegularPower);
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton3) )
    {
      SetPowerMultiplier(kHighPower);
    }
  */




		//	Drive
		//OmniArcadeDrive(primary.rightJoystick, primary.leftJoystick);	//	right = arcade, left = sidewind
		//OmniStrafeDrive(primary.leftJoystick, primary.rightJoystick);	//	left = strafe, right = turn




    //  tank drive
    SetMotorPower(Left, controller.leftJoystick.y);
    SetMotorPower(Right, controller.rightJoystick.y);






    /*

    bool r1, r2, l1, l2, left, right;

	  r1 = ControllerButtonIsPressed(primary, ControllerButtonR1);
	  r2 = ControllerButtonIsPressed(primary, ControllerButtonR2);
	  l1 = ControllerButtonIsPressed(primary, ControllerButtonL1);
	  l2 = ControllerButtonIsPressed(primary, ControllerButtonL2);

    if ( r1 ) OmniSetStrafePower(.5);
    else if ( r2 ) OmniSetStrafePower(1);
    else if ( l1 ) OmniSetStrafePower(-.5);
    else if ( l2 ) OmniSetStrafePower(-1);

    */



}

void MechanismControl(Controller& controller)
{
   //  slide adjustment
    if ( controller.dPad.y == 1 && !MechanismSlideIsMoving())
    {
      StartTask(MechanismSlideIncrementPosition);
    }
    else if ( controller.dPad.y == -1 && !MechanismSlideIsMoving() )
    {
      StartTask(MechanismSlideDecrementPosition);
    }



    //  kicker
		if ( !MechanismIsKicking() && ControllerButtonIsPressed(controller, ControllerButtonR1) )
		{
		  StartTask(MechanismKickBaton);
		}


		//  conveyor
		if ( !MechanismConveyorIsRunning() && ControllerButtonIsPressed(controller, ControllerButtonL1) )
		{
		  StartTask(MechanismCycleConveyor);
		}


		//  magnet slide position
		if ( ControllerButtonIsPressed(controller, ControllerButton4) )
		{
		  MechanismSlideSetMagnetPosition();
		}


		//  regular slide position
		if ( ControllerButtonIsPressed(controller, ControllerButton2) )
		{
		  MechanismSlideSetRegularPosition();
		}

		//  down position
		if ( ControllerButtonIsPressed(controller, ControllerButton3) )
		{
		  MechanismSlideSetDownPosition();
		}

		//  long position
		if ( ControllerButtonIsPressed(controller, ControllerButton1)
		{
		  MechanismSlideSetLongPosition();
		}
}






task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase



	/*
	while ( true )
	{
	  if ( MagneticSensorMagnetIsPresent() )
	  {
	    PlaySound(soundBeepBeep);
	  }
	}

	*/


	while (true)
	{
		Controller primary, secondary;
		UpdatePrimaryController(primary);
		UpdateSecondaryController(secondary);

    //DriveControl(primary);
    MechanismControl(secondary);
	}
}
