#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ElevatorBottomStop,     sensorTouch)
#pragma config(Sensor, S3,     SMUX2,               sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX1,               sensorI2CCustom)
#pragma config(Motor,  motorA,          IndicatorLight, tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  motorC,          ,              tmotorNormal, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Elevator,      tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Intake,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    Kicker,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    LeftStomper,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    Flap,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    Slide,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    RightStomper,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//  SMUX1
#define Magnet msensor_S4_3
#define LeftLightSensor msensor_S4_2
#define RightLightSensor msensor_S4_1
#define IR msensor_S4_4


//  SMUX2
#define ElevatorTopStop msensor_S3_1
#define Accelerometer msensor_S3_4


#include "shared/include.c"
#include "TeleOp/include.c"


void initializeRobot()
{
  //  init smuxi
  HTSMUXinit();
  HTSMUXscanPorts(SMUX1);
  HTSMUXscanPorts(SMUX2);


	AbortIfNoSMUX();

	MechanismInit();

	DrivePowerMultiplier = 1;

	return;
}





void DriveControl(Controller& controller)
{

}



#define kSlideIncrement -1

void MechanismControl(Controller& controller)
{
    //  intake
    if ( controller.leftJoystick.y > .25 )
    {
      servo[Intake] = kIntakeReverse;
    }
    else if ( controller.leftJoystick.y < -.25 )
    {
      servo[Intake] = kIntakeOn;
    }
    else
    {
      servo[Intake] = kIntakeOff;
    }



    if ( MechanismElevatorIsTargeting == false )
    {
      if ( ControllerButtonIsPressed(controller, ControllerButton2) )
      {
        //ABORT_ELEVATOR_TARGET();
        MechanismElevatorTargetEncoder = kElevatorTargetMidDispenser;
        StartTask(MechanismElevatorTargetTask);
      }
    }
}



task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		Controller primary, secondary;
		UpdatePrimaryController(primary);
		UpdateSecondaryController(secondary);

		if ( primary.isFresh || secondary.isFresh )
		{
		  DriveControl(primary);
		  MechanismControl(secondary);
    }

		//nxtDisplayCenteredTextLine(0, (string)nMotorEncoder[Elevator]);


		//nxtDisplayCenteredTextLine(0, (string)HTMAGreadVal(Magnet));

    /*
		if ( MagnetBatonPresent() )
		{
			motor[IndicatorLight] = 100;  //  turn the light on
		}
		else
		{
			motor[IndicatorLight] = 0;
		}
		*/
	}
}
