#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Magnetic,            sensorHiTechnicMagnetic)
#pragma config(Sensor, S3,     Sonar,               sensorSONAR)
#pragma config(Sensor, S4,     Accelerometer,       sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          Conveyor,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          IndicatorLight, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    Slide,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    Kicker,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    Door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#include "shared/include.c"
#include "TeleOp/include.c"


void initializeRobot()
{
	MechanismInit();

	DrivePowerMultiplier = 1;

	return;
}





void DriveControl(Controller& controller)
{
    //  power
    if ( ControllerButtonIsPressed(controller, ControllerButton1) )
    {
		DrivePowerMultiplier = kDrivePowerLow;
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
    {
		DrivePowerMultiplier = kDrivePowerNormal;
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton3) )
    {
		DrivePowerMultiplier = kDrivePowerHigh;
    }


    //  tank drive
    SetMotorPower(Left, controller.leftJoystick.y);
    SetMotorPower(Right, controller.rightJoystick.y);



	/*
    //  omni strafe
    bool r1, r2, l1, l2, left, right;
	  r1 = ControllerButtonIsPressed(controller, ControllerButtonR1);
	  r2 = ControllerButtonIsPressed(controller, ControllerButtonR2);
	  l1 = ControllerButtonIsPressed(controller, ControllerButtonL1);
	  l2 = ControllerButtonIsPressed(controller, ControllerButtonL2);

    if ( r1 ) OmniSetStrafePower(-.5);
    else if ( r2 ) OmniSetStrafePower(-1);
    else if ( l1 ) OmniSetStrafePower(.5);
    else if ( l2 ) OmniSetStrafePower(1);
    else OmniSetStrafePower(0);
	*/
}

void MechanismControl(Controller& controller)
{
    //  slide adjustment
    if ( controller.dPad.y == 1 && !MechanismSlideIsMoving)
    {
		StartTask(MechanismSlideIncrementPosition);
    }
    else if ( controller.dPad.y == -1 && !MechanismSlideIsMoving )
    {
		StartTask(MechanismSlideDecrementPosition);
    }



    //  kicker
	if ( !MechanismIsKicking && ControllerButtonIsPressed(controller, ControllerButtonR1) )
	{
		StartTask(MechanismKickBaton);
	}





	//  conveyor
	if ( ControllerButtonIsPressed(controller, ControllerButtonL1) )		//	forward
	{
		motor[Conveyor] = 50;
	}
	else if ( ControllerButtonIsPressed(controller, ControllerButtonL2) )	//	reverse
	{
		motor[Conveyor] = -50;
	}
	else																	//	stop
	{
		motor[Conveyor] = 0;
	}




	//  magnet slide position
	if ( ControllerButtonIsPressed(controller, ControllerButton4) )
	{
		MechanismSlideSetPosition(kSlideMagnetPosition);
	}

	//  regular slide position
	if ( ControllerButtonIsPressed(controller, ControllerButton2) )
	{
		MechanismSlideSetPosition(kSlideRegularPosition);
	}

	//  down position
	if ( ControllerButtonIsPressed(controller, ControllerButton3) )
	{
		MechanismSlideSetPosition(kSlideDownPosition);
	}

	//  long position
	if ( ControllerButtonIsPressed(controller, ControllerButton1)
	{
		MechanismSlideSetPosition(kSlideLongPosition);
	}
}






task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase


	while (true)
	{
		Controller primary, secondary;
		UpdatePrimaryController(primary);
		UpdateSecondaryController(secondary);

		DriveControl(primary);
		MechanismControl(secondary);


		if ( MagneticSensorMagnetIsPresent() )
		{
			motor[IndicatorLight] = 100;  //  turn the light on
		}
		else
		{
			motor[IndicatorLight] = 0;
		}
	}
}
