#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ElevatorTopStop,     sensorTouch)
#pragma config(Sensor, S3,     Sonar,               sensorSONAR)
#pragma config(Sensor, S4,     Accelerometer,       sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          IndicatorLight, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Elevator,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Empty,         tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    DoorLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    DoorRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Kicker,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    Slide,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



#define Magnetic 9

#include "shared/include.c"
#include "TeleOp/include.c"


void initializeRobot()
{
	MechanismInit();

	DrivePowerMultiplier = 1;

	return;
}





void DriveControl(Controller& controller)
{
    //  power
    if ( ControllerButtonIsPressed(controller, ControllerButton1) )
    {
		  DrivePowerMultiplier = kDrivePowerLow;
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton2) )
    {
		  DrivePowerMultiplier = kDrivePowerNormal;
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButton3) )
    {
		  DrivePowerMultiplier = kDrivePowerHigh;
    }


    //  tank drive
    SetMotorPower(Left, controller.leftJoystick.y);
    SetMotorPower(Right, controller.rightJoystick.y);
}

void MechanismControl(Controller& controller)
{

    //  slide adjustment
    if ( controller.dPad.x == -1 && !MechanismSlideIsMoving)
    {
		  StartTask(MechanismSlideIncrementPosition);
    }
    else if ( controller.dPad.x == 1 && !MechanismSlideIsMoving )
    {
		  StartTask(MechanismSlideDecrementPosition);
    }



    if ( ControllerButtonIsPressed(controller, ControllerButtonR1) )
    {
      servo[Kicker] = kKickerSpeed;
      PlaySoundFile("ChaChing.rso");
    }
    else
    {
      servo[Kicker] = kKickerStopped;
    }



    if ( ControllerButtonIsPressed(controller, ControllerButtonL1) && !ElevatorIsAtTop )
    {
      motor[Elevator] = kElevatorSpeed;
    }
    else if ( ControllerButtonIsPressed(controller, ControllerButtonL2) )
    {
      motor[Elevator] = -kElevatorSpeed;
    }
    else
    {
      motor[Elevator] = 0;
    }

	//  magnet slide position
	if ( ControllerButtonIsPressed(controller, ControllerButton4) )
	{
		MechanismSlideSetPosition(kSlideMagnetPosition);
	}

	//  regular slide position
	if ( ControllerButtonIsPressed(controller, ControllerButton2) )
	{
		MechanismSlideSetPosition(kSlideRegularPosition);
	}

	//  down position
	if ( ControllerButtonIsPressed(controller, ControllerButton3) )
	{
		MechanismSlideSetPosition(kSlideDownPosition);
	}

	//  long position
	if ( ControllerButtonIsPressed(controller, ControllerButton1)
	{
		MechanismSlideSetPosition(kSlideLongPosition);
	}


  //  trap door on magazine
	if ( controller.dPad.y == -1 )
	{
	  MechanismDoorSetPosition(kDoorDownPosition);
  }
  else if ( controller.dPad.y == 1 )
  {
    MechanismDoorSetPosition(kDoorUpPosition);
  }
  else
  {
    MechanismDoorSetPosition(kDoorFlatPosition);
  }


}


task vibrate()
{
  while ( true )
  {
    servo[DoorRight] = 200;
    wait1Msec(200);
    servo[DoorRight] = 0;
  }
}



task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase



	while (true)
	{
		Controller primary, secondary;
		UpdatePrimaryController(primary);
		UpdateSecondaryController(secondary);

		DriveControl(primary);
		MechanismControl(secondary);




		if ( MagneticSensorMagnetIsPresent() )
		{
			motor[IndicatorLight] = 100;  //  turn the light on
		}
		else
		{
			motor[IndicatorLight] = 0;
		}
	}
}
