#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTSMUX,              sensorNone)
#pragma config(Sensor, S3,     Accelerometer,       sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          Conveyor,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          IndicatorLight, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Front,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Back,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Kicker,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    Slide,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#include "shared/include.c"
#include "Autonomous/include.c"
//#include "TeleOp/include.c"
#include "HT RobotC Drivers/drivers/HTAC-driver.h"



bool f1()
{
  return true;
}

bool f2()
{
  return true;
}

bool f3()
{
  return true;
}

bool f4()
{
  return true;
}

bool f5()
{
  return true;
}

bool f6()
{
  return true;
}

bool f7()
{
  return true;
}

bool f8()
{
  return true;
}

bool f9()
{
  return true;
}

bool f10()
{
  return true;
}

bool f11()
{
  return true;
}

bool f12()
{
  return true;
}

bool f21()
{
  return true;
}

bool f22()
{
  return true;
}

bool f23()
{
  return true;
}

bool f24()
{
  return true;
}

bool f25()
{
  return true;
}

bool f26()
{
  return true;
}

bool f27()
{
  return true;
}

bool f28()
{
  return true;
}

bool f29()
{
  return true;
}

bool f210()
{
  return true;
}

bool f121()
{
  return true;
}

bool f122()
{
  return true;
}

bool f294()
{
  return true;
}

bool f259()
{
  return true;
}

bool f269()
{
  return true;
}

bool f297()
{
  return true;
}

bool f298()
{
  return true;
}

bool f299()
{
  return true;
}

bool f2190()
{
  return true;
}

bool f1291()
{
  return true;
}

bool f1292()
{
  return true;
}




task main()
{



 f1();
 f2();

 wait10Msec(1000);



}
