#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Kicker,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//









#define kKickerServoDownPosition 255
#define kKickerServoUpPosition 255 - 65





task main()
{


  bool up;


  while ( true )
  {
    servo[Kicker] = (up) ? kKickerServoUpPosition : kKickerServoDownPosition;
    up = ( up ) ? false : true;
    wait10Msec(40);
  }


  servo[Kicker] = 255;


  wait10Msec(4000);


}
