#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Front,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Back,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Servo1,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void followIRAtSpeed(float speed)
{
	while ( true )	//	repeat forever
	{
		if ( SensorValue[IR] == 0 )	//	we can't sense the ir transmitter, so we'll just sit still
		{
			motor[Left] = 0;
			motor[Right] = 0;
		}
		else						//	we can sense the ir, so we'll turn towards it
		{
			float error = 5 - SensorValue[IR];	//	see how far the IR is off from the center

			float rotation = (speed / 4) * error;

			motor[Left] = speed - rotation;
			motor[Right] = speed + rotation;
		}
	}
}






task main()
{
	followIRAtSpeed(30);
}
