#pragma config(Sensor, S1,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




void followIRAtSpeed(float speed)
{
	while ( true )	//	repeat forever
	{
		if ( SensorValue[IR] == 0 )	//	we can't sense the ir transmitter, so we'll just sit still
		{
			motor[Left] = 0;
			motor[Right] = 0;
		}
		else						//	we can sense the ir, so we'll turn towards it
		{
			float error = 5 - SensorValue[IR];	//	see how far the IR is off from the center
			
			float rotation = (speed / 4) * error;
			
			motor[Left] = speed - rotation;
			motor[Right] = speed + rotation;
		}
	}
}






task main()
{
	followIRAtSpeed(50);
}

