#pragma config(Sensor, S1,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "../Advanced/include.c"
#include "../Common/include.c"



task main()
{
	LogShow();
	
	
	for ( int i = 0; i < 2000; i++ )
	{
		string str;
		StringFormat(str, "Log line %d", i);
		LogString(str);
		wait10MSec(175);
	}
	
	
	
	
	
	
	
}

