#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Front,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Back,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Servo1,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while ( true )
 {
   servo[Servo1] = SensorValue[IR] * 15;
   //wait10Msec(50);
 }
}
