#pragma config(Sensor, S1,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//





task main()
{
	
	
	
	
	
	
	
	
	
	
	
}

