#pragma config(Motor,	 motorA,					Left,					 tmotorNormal, PIDControl, encoder)
#pragma config(Motor,	 motorB,					Right,				 tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//


#include "../Common/include.c"
#include "../Advanced/include.c"

task main()
{
	Controller c;

	while ( true )
	{
		UpdatePrimaryController(c);
		float speed = (ControllerButtonIsToggledOn(c, ControllerButton2)) ? 100 : 50;


		nxtDisplayTextLine(0, (string)c.dPad.y);

		motor[Left] = speed * c.leftJoystick.y;
		motor[Right] = speed * c.rightJoystick.y;
	}
}
